site_name: Lagom - Depdency Injection Container
repo_url: https://github.com/meadsteve/lagom
theme:
  name: 'material'
  palette:
    primary: green
    accent: pink

nav:
  - Usage:
    - Getting Started: index.md
    - Framework Integrations: framework_integrations.md
    - Testing Code Using Lagom: testing_with_lagom.md
    - Experimental Features: experimental.md
    - Cookbook & Common Usage Patterns: cookbook.md
    - Comparison to Alternatives: comparison.md
    - App Example: full_example.md
  - Development:
    - Contributing: development_of_lagom.md
    - Change Log: CHANGELOG.md
    - Github: https://github.com/meadsteve/lagom
    - Issue Tracker: https://github.com/meadsteve/lagom/issues

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - codehilite